### 변수 설정
@baseUrl = http://localhost:{{$dotenv PORT}}/api

### 시딩 후 로그 보고 복붙
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtbGlwY3UydDAwMDJ2ODh0eG40b3VidmgiLCJlbWFpbCI6ImN1c3RvbWVyQHRlc3QuY29tIiwicm9sZSI6IkNVU1RPTUVSIiwiaWF0IjoxNzcwODU1MDIwLCJleHAiOjE3NzA5NDE0MjB9.K5ELc3ZMYm6EZGZo56S8fXV1axaGMBO70vtXgGNoFMI
@sellerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtbGlwY3UwZTAwMDB2ODh0bmhxb2IxcmIiLCJlbWFpbCI6InNlbGxlckB0ZXN0LmNvbSIsInJvbGUiOiJTRUxMRVIiLCJpYXQiOjE3NzA4NTUwMjAsImV4cCI6MTc3MDk0MTQyMH0.xItKMKPiyS_4Ki6gwMhK3lpsWc__BnzHH8S0zhMIJQQ  
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtbGlwY3UxcDAwMDF2ODh0a2ZyeDJmbnoiLCJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzcwODU1MDIwLCJleHAiOjE3NzA5NDE0MjB9.zKmNMjkQjp8fnSxEo-9Gmb2CiBGkVkKO6eM-u6HC7Ig

@classId = cmlj8jlck0008vg8twpvj5j36
@slotId = cmlj8jycc0009vg8teje5g20l

### 1. 클래스 생성 (판매자)
POST {{baseUrl}}/classes
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
Authorization: Bearer {{sellerToken}}

------WebKitFormBoundary
Content-Disposition: form-data; name="title"

테스트요가클래스
------WebKitFormBoundary
Content-Disposition: form-data; name="category"

요가
------WebKitFormBoundary
Content-Disposition: form-data; name="level"

초급
------WebKitFormBoundary
Content-Disposition: form-data; name="description"

요가 초급 클래스입니다
------WebKitFormBoundary
Content-Disposition: form-data; name="notice"

수업 10분 전 도착 부탁드립니다
------WebKitFormBoundary
Content-Disposition: form-data; name="pricePoints"

10000
------WebKitFormBoundary
Content-Disposition: form-data; name="capacity"

20
------WebKitFormBoundary
Content-Disposition: form-data; name="images"; filename="image1.png"
Content-Type: image/png

< test/image1.png
------WebKitFormBoundary
Content-Disposition: form-data; name="images"; filename="image2.png"
Content-Type: image/png

< test/image2.png
------WebKitFormBoundary
Content-Disposition: form-data; name="images"; filename="image3.png"
Content-Type: image/png

< test/image3.png
------WebKitFormBoundary--


### 1-1. 클래스 통계 조회 (관리자)
GET {{baseUrl}}/classes/stats
Authorization: Bearer {{adminToken}}

### 2. 클래스 목록 조회
GET {{baseUrl}}/classes

### 3. 클래스 목록 조회 (필터링)
GET {{baseUrl}}/classes?category=요가&level=초급&page=1&limit=10

### 3-1. 클래스 목록 조회 (검색)
GET {{baseUrl}}/classes?search=요가


### 4. 클래스 수정 (판매자)
PATCH {{baseUrl}}/classes/{{classId}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
Authorization: Bearer {{sellerToken}}

------WebKitFormBoundary
Content-Disposition: form-data; name="title"

수정된 요가 클래스
------WebKitFormBoundary
Content-Disposition: form-data; name="description"

설명이 수정되었습니다
------WebKitFormBoundary
Content-Disposition: form-data; name="capacity"

25
------WebKitFormBoundary
Content-Disposition: form-data; name="pricePoints"

12000
------WebKitFormBoundary
Content-Disposition: form-data; name="images"; filename="image1.png"
Content-Type: image/png

< test/image1.png
------WebKitFormBoundary
Content-Disposition: form-data; name="images"; filename="image2.png"
Content-Type: image/png

< test/image2.png
------WebKitFormBoundary--

### 5. 클래스 승인 (관리자)
PATCH {{baseUrl}}/classes/{{classId}}/approve
Content-Type: application/json
Authorization: Bearer {{adminToken}}


### 6. 클래스 반려 (관리자)
PATCH {{baseUrl}}/classes/{{classId}}/reject
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "rejectReason": "클래스 정보가 부족합니다"
}

### 7. 클래스 상세 조회
GET {{baseUrl}}/classes/{{classId}}

### 8. 슬롯 생성 (판매자)
POST {{baseUrl}}/classes/{{classId}}/slots
Content-Type: application/json
Authorization: Bearer {{sellerToken}}

{
  "date": "2026-02-25",
  "hour": 8,
  "capacity": 15,
  "isOpen": true
}

### 9. 슬롯 수정 (판매자)
PATCH {{baseUrl}}/classes/{{classId}}/slots/{{slotId}}
Content-Type: application/json
Authorization: Bearer {{sellerToken}}

{
  "isOpen": false
}

### 10. 슬롯 삭제 (판매자)
DELETE {{baseUrl}}/classes/{{classId}}/slots/{{slotId}}
Authorization: Bearer {{sellerToken}}

### 11. 클래스 삭제 (판매자)
DELETE {{baseUrl}}/classes/{{classId}}
Authorization: Bearer {{sellerToken}}
